# Generated by Django 5.1.4 on 2025-01-09 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo', null=True, upload_to='provider_logos/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='services_offered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
