# Generated by Django 5.1.4 on 2025-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_providerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
