# Generated by Django 5.1.4 on 2025-01-08 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_options_rename_user_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
